final before mentor review
RadkoIvanUa/nodejs-homework pull request #1
Opened 2023-08-11 18:41 UTC by RadkoIvanUa

2023-08-12 09:21 UTC, ceREAL133 requested changes

2023-08-12 09:21 UTC, ceREAL133 commented on schemas/bodySchema.js
> +  email: Joi.string().required(),
you should validate email and phone properly

2023-08-12 09:23 UTC, RadkoIvanUa commented on schemas/bodySchema.js
> +  email: Joi.string().required(),
правильно це як?

2023-08-13 09:40 UTC, ceREAL133 approved these changes

2023-08-13 09:41 UTC, ceREAL133 commented on schemas/bodySchema.js
> +  email: Joi.string().required(),
це так, щоб імейл і телефон не могли бути будь-якою строкою

2023-08-13 20:43 UTC, merged